### ISSUE TITLE
la sutysisku dark mode compatibility

### ISSUE THREAD

**Issue by NathanHawks** [lagleki/livla#557]
The gradient background on la sutysisku is a nice achievement but unfortunately it adds a lot of unwanted contrast when viewing with "dark mode" enabled in the browser. May I suggest changing the CSS for .content so that:

- the gradient is removed
- the background is simply #DDDDDD

Also, the background-size attribute becomes superfluous with these changes.

The result in dark mode looks like this:

![image](https://user-images.githubusercontent.com/1900336/136002298-6c182a3b-7aa2-4957-8e69-c90f67f85781.png)

**Comment by NathanHawks** [comment]
```
.content {
  padding-left: 5px;
  padding-right: 5px;
  overflow: auto;
  box-sizing: border-box;
  background: #DDDDDD;
}
```

**Comment by NathanHawks** [comment]
```
@media (prefers-color-scheme: dark)
.content {
  background: #DDDDDD;
}
.content {
  padding-left: 5px;
  padding-right: 5px;
  overflow: auto;
  box-sizing: border-box;
  background: #222222
    linear-gradient(
      -45deg,
      rgba(255, 255, 255, 0.15) 25%,
      transparent 25%,
      transparent 50%,
      rgba(255, 255, 255, 0.15) 50%,
      rgba(255, 255, 255, 0.15) 75%,
      transparent 75%,
      transparent
    );
  background-size: 40px 40px !important;
}
```

**Comment by NathanHawks** [comment]
Note for other interested parties: dark mode addons **reverse** the color scheme, so #DDDDDD becomes a charcoal color.

**Comment by NathanHawks** [comment]
@media (prefers-color-scheme: dark) {
  .content {
    background: #DDDDDD;
  }
}
.content {
  padding-left: 5px;
  padding-right: 5px;
  overflow: auto;
  box-sizing: border-box;
  background: #222222
    linear-gradient(
      -45deg,
      rgba(255, 255, 255, 0.15) 25%,
      transparent 25%,
      transparent 50%,
      rgba(255, 255, 255, 0.15) 50%,
      rgba(255, 255, 255, 0.15) 75%,
      transparent 75%,
      transparent
    );
  background-size: 40px 40px !important;
}

**Comment by NathanHawks** [comment]
Dark mode:

![image](https://user-images.githubusercontent.com/1900336/136013218-47054622-8835-4ccc-a3e5-4c900cd3a28c.png)

Light mode:

![image](https://user-images.githubusercontent.com/1900336/136013376-4970a7a6-381a-4706-9466-567589f3e5f2.png)

**Comment by lagleki** [comment]
fixed in https://github.com/lagleki/livla/commit/4b7c395dcc0bcedfdbe7fafba611b614ab346fa0
