### ISSUE TITLE
Multiple word search (phrase search) 

### ISSUE THREAD

**Issue by NathanHawks** [lagleki/livla#560]
Would it be possible for la sutysisku to support search terms with spaces?

For example "facial expression"

**Comment by lagleki** [comment]
Currently it only works in regexp mode. For normal mode we need to design a
mechanism: is our search
1. a phrase in lojban that needs to be decomposed or it's a zei lujvo
2. or its an English phrase or any other sequence of words that some
definitions contains.

Maybe search for both options by default but put a short clickable
expandable card listing how many results for options 2. are found and after
that card put the results from options 1. fully expanded
