### ISSUE TITLE
In "Last searched" history, selmaho searches should be a different color

### ISSUE THREAD

**Issue by NathanHawks** [lagleki/livla#565]
Perhaps black with a grey background, matching the button?

**Comment by lagleki** [comment]
currently typing anything in the search field switches the search mode to the normal mode corresponding to pressing "search" button.

**Comment by NathanHawks** [comment]
> currently typing anything in the search field switches the search mode to
the normal mode corresponding to pressing "search" button.

Verified working on live after a force-refresh

> selmaho searches should be a different color

Still hoping for this (or is it already done in beta?)
