### ISSUE TITLE
Submit Language Registration

### ISSUE THREAD

**Issue by Pantyhose-X** [lagleki/livla#573]
Submit language registration to https://www.omniglot.com/index.htm

**Comment by Pantyhose-X** [comment]
Please read https://www.omniglot.com/conscripts/howto.htm

**Comment by lagleki** [comment]
please describe clearly what you are proposing.

Em seg., 20 de dez. de 2021 às 17:24, Pantyhose-X ***@***.***>
escreveu:

**Comment by lagleki** [comment]
no reply. closing. feel free to reopen when you have precise suggestions.
